Adding some more readme
makiftutuncu/spring-boot-crud pull request #4
Opened 2023-02-03 20:15 UTC by arnokoehler

2023-02-04 11:19 UTC, makiftutuncu requested changes
Awesome work! I made some comments, mostly about the correctness of the examples. Otherwise, it's a great start to user documentation. 🥳

2023-02-04 11:19 UTC, makiftutuncu commented on README.md
> +You may choose to use one of the variants of CRUDController such as CRUDControllerSimple, CRUDControllerSimpler, or CRUDControllerSimplest depending on your needs.
Class names weren't correct so following might be better.
```suggestion
If you need all the flexibility `CRUDController` provides, you may choose to use one of the following variants `SimpleController`, `SimplerController`, or `SimplestController`.
```

2023-02-04 11:19 UTC, makiftutuncu commented on README.md
> +The code snippet represents a Java Controller that implements the CRUDController interface.
`CRUDController` is an abstract class so this statement and following example would need to be updated.

2023-02-04 11:19 UTC, makiftutuncu commented on README.md
> +- `DTOMappe`r: the type of the mapper class used to map between DTO and Model objects
Small typo
```suggestion
- `DTOMapper`: the type of the mapper class used to map between DTO and Model objects
```

2023-02-04 11:19 UTC, makiftutuncu commented on README.md
> +public class ExampleService implements CRUDService<
`CRUDService` is an abstract class so this statement and following example would need to be updated.

2023-02-04 11:19 UTC, makiftutuncu commented on README.md
> +```java
Is this example is here to show roughly what `CRUDService` provides?

If the answer is yes, this is fine but we should probably mention the fact that this is not the expected user code, it is here to give you an idea of what the library is doing.

If the answer is no and this is an example of the user code, then we have some redundancy. User code could (and should) be as simple as following
```java
@Service
public class ExampleService extends CRUDService<
                Long, 
                ExampleModel, 
                ExampleEntity, 
                ExampleCreateModel,
                ExampleUpdateModel, 
                ExampleMapper> {
    public ExampleService(Clock clock, ExampleRepository repository, ExampleMapper mapper) {
        super("Example", clock, repository, mapper);
    }
}
```

The same question applies to the controller example above.

2023-02-04 11:19 UTC, makiftutuncu commented on README.md
> +| GET	 | /api/v1/examples	        | Retrieve a list of examples |
This table is great but controller example above would need to have `@RequestMapping("api/v1/examples")`.

2023-02-04 11:40 UTC, makiftutuncu commented
FYI, I just merged https://github.com/makiftutuncu/spring-boot-crud/pull/3 so links to files would also need to be updated.

2023-02-04 12:47 UTC, arnokoehler commented
I'll see what I can do, today or tomorrow.

On Sat, Feb 4, 2023, 12:40 Mehmet Akif Tütüncü ***@***.***>
wrote:

> FYI, I just merged #3
> <https://github.com/makiftutuncu/spring-boot-crud/pull/3> so links to
> files would also need to be updated.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/makiftutuncu/spring-boot-crud/pull/4#issuecomment-1416730449>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABN6LCIX73UCEGZ7UB6GROLWVY52FANCNFSM6AAAAAAUQU3Y4A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-27 13:51 UTC, makiftutuncu approved these changes

2023-02-27 13:54 UTC, merged